spring:
  dubbo:
    application:
      name: easybook-consumer
    registry:
      address: zookeeper://127.0.0.1:2181
      protocol: zookeeper
#    monitor:
#      protocol: registry
    server:
      port: 8081
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 3000
    lettuce:
      pool:
        max-active: 8
        # 最大阻塞等待时间
        max-wait: -1
        max-idle: 8
        min-idle: 0
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      retries: 3
      acks: 1 # 应答级别:多少个分区副本备份完成时向生产者发送ack确认(可选0、1、all/-1)
      batch-size: 16384
      properties:
        linger:
          ms: 0
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


  web:
    resources:
      static-locations: file:${oss.store-path}
  mvc:
    static-path-pattern: /static/**

server:
  port: 8088

oss:
  store-path: /Users/pengfeng/Desktop/EasyBook/files
  url-prefix: http://localhost:8088/static/
